import { useEffect, useMemo, useState } from "react";
import { api } from "../services/api";

import PageShell from "../components/ui/PageShell";
import SectionCard from "../components/ui/SectionCard";
import StatCard from "../components/ui/StatCard";
import Badge from "../components/ui/Badge";
import EmptyState from "../components/ui/EmptyState";
import ResponsiveRow from "../components/ui/ResponsiveRow";

function fmtMoney(value) {
  return `$${Number(value || 0).toLocaleString()}`;
}

function normalizeList(data, keys = []) {
  if (Array.isArray(data)) return data;

  for (const key of keys) {
    if (Array.isArray(data?.[key])) return data[key];
  }

  return data?.results || data?.vendors || data?.rows || [];
}

function severityTone(value) {
  const v = String(value || "").toLowerCase();
  if (v === "high" || v === "critical" || v === "elevated") return "danger";
  if (v === "medium" || v === "watch") return "demo";
  return "accent";
}

function getActionKey(action = {}, fallback = "") {
  return String(action.id || `${action.state || "National"}-${action.title || fallback || "vendor-action"}`);
}

function VendorRow({ vendor }) {
  const name = vendor.name || vendor.vendor_name || "Unnamed Vendor";
  const category = vendor.category || "Campaign Vendor";
  const state = vendor.state || vendor.primary_state || "Unknown";
  const services =
    vendor.services ||
    vendor.capabilities ||
    vendor.description ||
    "Campaign operations and political services";

  return (
    <div className="vs-premium-row-card">
      <ResponsiveRow
        title={name}
        subtitle={`${state} • ${category}`}
        meta={[
          { label: "Coverage", value: vendor.coverage_area || state || "—" },
          { label: "Contract", value: fmtMoney(vendor.contract_value) },
          { label: "Services", value: services }
        ]}
        right={<Badge tone="accent">{vendor.status || "active"}</Badge>}
      />
    </div>
  );
}

function RiskRow({ item }) {
  const severity = item.severity || item.priority || "Medium";

  return (
    <div className={`vs-premium-row-card ${severity === "High" ? "is-elevated" : ""}`}>
      <ResponsiveRow
        title={item.title || "Vendor intelligence signal"}
        subtitle={item.detail || "Review vendor coverage and operational readiness."}
        meta={[
          { label: "Severity", value: severity },
          { label: "State", value: item.state || "National" }
        ]}
        right={<Badge tone={severityTone(severity)}>{severity}</Badge>}
      />
    </div>
  );
}

function ActionTaskRow({ action, onCreateTask, creating, taskExists }) {
  const severity = action.priority || action.severity || "Medium";

  return (
    <div className={`vs-premium-row-card ${severity === "High" ? "is-elevated" : "is-action"}`}>
      <ResponsiveRow
        title={action.title || "Review vendor coverage"}
        subtitle={action.detail || "Generated by vendor scoring."}
        meta={[
          { label: "Owner", value: action.owner || "Operations" },
          { label: "Due", value: action.due || "This Week" },
          { label: "State", value: action.state || "National" }
        ]}
        right={
          taskExists ? (
            <Badge tone="demo">Task Exists</Badge>
          ) : (
            <button
              type="button"
              className="vs-decision-btn deploy"
              disabled={creating}
              onClick={() => onCreateTask(action)}
            >
              {creating ? "Creating..." : "Create Task"}
            </button>
          )
        }
      />
    </div>
  );
}

export default function Vendors() {
  const [rows, setRows] = useState([]);
  const [states, setStates] = useState([]);
  const [categories, setCategories] = useState([]);
  const [statuses, setStatuses] = useState([]);
  const [intel, setIntel] = useState(null);

  const [loading, setLoading] = useState(true);
  const [intelLoading, setIntelLoading] = useState(true);
  const [error, setError] = useState("");
  const [dispatchMessage, setDispatchMessage] = useState("");
  const [taskMessage, setTaskMessage] = useState("");
  const [creatingTaskId, setCreatingTaskId] = useState("");
  const [existingTaskIds, setExistingTaskIds] = useState(() => new Set());

  const [filters, setFilters] = useState({
    q: "",
    state: "",
    category: "",
    status: "",
    page: 1,
    limit: 12
  });

  useEffect(() => {
    let active = true;

    async function loadFilters() {
      try {
        const [stateData, categoryData, statusData] = await Promise.all([
          api.vendorStates?.(),
          api.vendorCategories?.(),
          api.vendorStatuses?.()
        ]);

        if (!active) return;

        setStates(normalizeList(stateData, ["states", "results"]));
        setCategories(normalizeList(categoryData, ["categories", "results"]));
        setStatuses(normalizeList(statusData, ["statuses", "results"]));
      } catch (err) {
        if (!active) return;
        setError(err?.message || "Failed to load vendor filters");
      }
    }

    loadFilters();

    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    let active = true;

    async function loadVendors() {
      try {
        setLoading(true);
        setError("");

        const data = await api.vendors(filters);

        if (!active) return;
        setRows(normalizeList(data, ["results", "vendors", "rows"]));
      } catch (err) {
        if (!active) return;
        setError(err?.message || "Failed to load vendors");
        setRows([]);
      } finally {
        if (active) setLoading(false);
      }
    }

    loadVendors();

    return () => {
      active = false;
    };
  }, [filters]);

  useEffect(() => {
    let active = true;

    async function loadIntel() {
      try {
        setIntelLoading(true);
        const data = await api.vendorScoring?.();
        if (!active) return;
        setIntel(data || null);
      } catch {
        if (!active) return;
        setIntel(null);
      } finally {
        if (active) setIntelLoading(false);
      }
    }

    loadIntel();

    return () => {
      active = false;
    };
  }, []);

  async function dispatchVendorAlerts() {
    try {
      setDispatchMessage("Dispatching vendor alerts...");
      const result = await api.dispatchVendorAlerts?.();
      setDispatchMessage(`Dispatched ${result?.dispatched || 0} vendor intelligence alerts.`);
    } catch (err) {
      setDispatchMessage(err?.message || "Failed to dispatch vendor alerts.");
    }
  }

  async function createVendorTask(action = {}) {
    const taskKey = getActionKey(action);

    try {
      setCreatingTaskId(taskKey);
      setTaskMessage(`Creating task: ${action.title || "Review vendor coverage"}`);

      const result = await api.createTask?.({
        title: action.title || "Review vendor coverage",
        description: action.detail || "Generated from Vendor Network intelligence.",
        source: "vendor_network",
        state: action.state || "National",
        office: "Statewide",
        priority: action.priority === "High" ? "high" : "medium",
        status: "open",
        assigned_to: action.owner || "Operations",
        due_label: action.priority === "High" ? "Today" : action.due || "This Week",
        metadata: {
          vendor_action_id: taskKey,
          vendor_action: action
        }
      });

      if (result?.duplicate) {
        setExistingTaskIds((prev) => {
          const next = new Set(prev);
          next.add(taskKey);
          return next;
        });
        setTaskMessage(`Task exists: ${action.title || "Review vendor coverage"}`);
        return;
      }

      setExistingTaskIds((prev) => {
        const next = new Set(prev);
        next.add(taskKey);
        return next;
      });
      setTaskMessage(`Task created: ${action.title || "Review vendor coverage"}`);
    } catch (err) {
      setTaskMessage(err?.message || "Failed to create vendor task.");
    } finally {
      setCreatingTaskId("");
    }
  }

  const summary = useMemo(() => {
    return intel?.summary || {
      total_vendors: rows.length,
      active_vendors: rows.filter((row) => String(row.status || "").toLowerCase() === "active").length,
      states_covered: new Set(rows.map((row) => row.state).filter(Boolean)).size,
      categories_covered: new Set(rows.map((row) => row.category).filter(Boolean)).size,
      high_gap_states: 0,
      medium_gap_states: 0
    };
  }, [intel, rows]);

  const gapCount = Number(summary.high_gap_states || 0) + Number(summary.medium_gap_states || 0);

  return (
    <PageShell
      eyebrow="Vendor Intelligence"
      title="Vendor Network"
      description="Live campaign vendor coverage, gap detection, operational readiness, and execution tasking."
      tickerItems={[
        { label: "Vendors", value: `${summary.total_vendors || 0} live`, dotClass: "vs-live-dot-success" },
        { label: "Coverage", value: `${summary.states_covered || 0} states`, dotClass: "vs-live-dot-warning" },
        { label: "Gaps", value: `${gapCount} flagged`, dotClass: gapCount ? "vs-live-dot" : "vs-live-dot-success" }
      ]}
    >
      <style>{`
        .vs-premium-row-card {
          border: 1px solid rgba(148, 163, 184, 0.16);
          border-radius: 18px;
          background: linear-gradient(135deg, rgba(15, 23, 42, 0.78), rgba(15, 23, 42, 0.48));
          box-shadow: 0 14px 34px rgba(2, 6, 23, 0.18);
          overflow: hidden;
          transition: transform 160ms ease, border-color 160ms ease, box-shadow 160ms ease;
        }

        .vs-premium-row-card:hover {
          transform: translateY(-1px);
          border-color: rgba(96, 165, 250, 0.32);
          box-shadow: 0 18px 42px rgba(2, 6, 23, 0.24);
        }

        .vs-premium-row-card.is-elevated {
          border-color: rgba(248, 113, 113, 0.32);
          background: linear-gradient(135deg, rgba(127, 29, 29, 0.22), rgba(15, 23, 42, 0.68));
        }

        .vs-premium-row-card.is-action {
          border-color: rgba(34, 197, 94, 0.18);
        }

        .vs-premium-row-card .vs-responsive-row {
          border: 0;
          background: transparent;
        }
      `}</style>

      {error ? <div className="vs-banner vs-banner-danger">{error}</div> : null}
      {dispatchMessage ? <div className="vs-banner">{dispatchMessage}</div> : null}
      {taskMessage ? <div className="vs-banner vs-live-banner-pulse">{taskMessage}</div> : null}

      <div className="vs-grid-4">
        <StatCard label="Total Vendors" value={summary.total_vendors || 0} delta="Live vendor records" tone="up" />
        <StatCard label="Active Vendors" value={summary.active_vendors || 0} delta="Ready capacity" tone="up" />
        <StatCard label="States Covered" value={summary.states_covered || 0} delta="Covered markets" tone="up" />
        <StatCard label="Gap States" value={gapCount} delta="Coverage pressure" tone={gapCount ? "down" : "up"} />
      </div>

      <SectionCard
        title="Vendor Controls"
        subtitle="Filter the live vendor network and dispatch vendor intelligence alerts."
        right={
          <button type="button" className="vs-decision-btn deploy" onClick={dispatchVendorAlerts}>
            Dispatch Vendor Alerts
          </button>
        }
      >
        <div className="vs-grid-4">
          <input
            className="vs-input"
            placeholder="Search vendors"
            value={filters.q}
            onChange={(e) => setFilters((prev) => ({ ...prev, q: e.target.value, page: 1 }))}
          />

          <select
            className="vs-input"
            value={filters.state}
            onChange={(e) => setFilters((prev) => ({ ...prev, state: e.target.value, page: 1 }))}
          >
            <option value="">All states</option>
            {states.map((item, index) => {
              const value = item.name || item.state || item;
              return (
                <option key={`${value}-${index}`} value={value}>
                  {value}
                </option>
              );
            })}
          </select>

          <select
            className="vs-input"
            value={filters.category}
            onChange={(e) => setFilters((prev) => ({ ...prev, category: e.target.value, page: 1 }))}
          >
            <option value="">All categories</option>
            {categories.map((item, index) => {
              const value = item.name || item.category || item;
              return (
                <option key={`${value}-${index}`} value={value}>
                  {value}
                </option>
              );
            })}
          </select>

          <select
            className="vs-input"
            value={filters.status}
            onChange={(e) => setFilters((prev) => ({ ...prev, status: e.target.value, page: 1 }))}
          >
            <option value="">All statuses</option>
            {statuses.map((item, index) => {
              const value = item.name || item.status || item;
              return (
                <option key={`${value}-${index}`} value={value}>
                  {value}
                </option>
              );
            })}
          </select>
        </div>
      </SectionCard>

      <div className="vs-grid-2">
        <SectionCard
          title="Live Vendor Directory"
          subtitle="Database-backed vendor network with operating coverage and status."
          right={<Badge tone="accent">{rows.length} shown</Badge>}
        >
          <div className="vs-stack">
            {loading ? (
              <EmptyState text="Loading vendors..." />
            ) : rows.length === 0 ? (
              <EmptyState text="No vendors found." />
            ) : (
              rows.map((vendor, index) => (
                <VendorRow
                  key={vendor.id ?? vendor.vendor_id ?? `${vendor.name || vendor.vendor_name}-${index}`}
                  vendor={vendor}
                />
              ))
            )}
          </div>
        </SectionCard>

        <div className="vs-stack">
          <SectionCard
            title="Coverage Gaps"
            subtitle="States where vendor bench strength is thin or missing."
            right={<Badge tone={gapCount ? "danger" : "accent"}>{gapCount} gaps</Badge>}
          >
            <div className="vs-stack">
              {intelLoading ? (
                <EmptyState text="Loading vendor intelligence..." />
              ) : !intel?.gaps?.length ? (
                <EmptyState text="No vendor coverage gaps detected." />
              ) : (
                intel.gaps.slice(0, 6).map((gap, index) => (
                  <RiskRow key={`${gap.state}-${index}`} item={gap} />
                ))
              )}
            </div>
          </SectionCard>

          <SectionCard
            title="Recommended Actions"
            subtitle="Create execution tasks directly from vendor intelligence."
            right={<Badge tone="demo">{intel?.recommended_actions?.length || 0} actions</Badge>}
          >
            <div className="vs-stack">
              {!intel?.recommended_actions?.length ? (
                <EmptyState text="No recommended vendor actions." />
              ) : (
                intel.recommended_actions.slice(0, 6).map((action, index) => {
                  const taskKey = getActionKey(action, index);

                  return (
                    <ActionTaskRow
                      key={taskKey}
                      action={action}
                      creating={creatingTaskId === taskKey}
                      taskExists={existingTaskIds.has(taskKey)}
                      onCreateTask={createVendorTask}
                    />
                  );
                })
              )}
            </div>
          </SectionCard>
        </div>
      </div>
    </PageShell>
  );
}
