export const navigationSections = [
  {
    label: "Workspace",
    featured: true,
    items: [
      { label: "Executive Workspace", to: "/executive-workspace" },
      { label: "Platform Tour", to: "/platform-tour" },
      { label: "Launch Automation", to: "/launch-automation" },
      { label: "Live Data Refresh", to: "/live-data-refresh" },
      { label: "Launch Data Seeder", to: "/launch-data-seeder" },
      { label: "Beta Onboarding", to: "/beta-onboarding" },
      { label: "Launch Assets", to: "/launch-assets" },
      { label: "Revenue Pipeline", to: "/revenue-pipeline" },
      { label: "Database Stability", to: "/database-stability" },
      { label: "Launch Readiness", to: "/launch-readiness" },
      { label: "Launch QA", to: "/launch-qa" },
      { label: "Production Hardening", to: "/production-hardening" },
      { label: "Live Intelligence Layer", to: "/live-intelligence-layer" },
      { label: "Opportunity Engine", to: "/opportunity-engine" },
      { label: "Universal Search", to: "/search" },
      { label: "Notifications", to: "/notifications" },
      { label: "National Command", to: "/national-command" },
    ],
  },
  {
    label: "Intelligence",
    items: [
      { label: "Political Intelligence Graph", to: "/political-intelligence" },
      { label: "AI Campaign Co-Pilot", to: "/campaign-copilot" },
      { label: "Strategic Advisor", to: "/strategic-advisor" },
      { label: "Election Forecast", to: "/forecast" },
      { label: "Donor Network", to: "/donors" },
      { label: "Candidates", to: "/candidates" },
    ],
  },
  {
    label: "Operations",
    items: [
      { label: "Command Center", to: "/command-center" },
      { label: "Mission Control", to: "/mission-control" },
      { label: "War Room", to: "/war-room" },
      { label: "Campaign CRM", to: "/campaign-crm" },
      { label: "Vendor Network", to: "/vendors" },
      { label: "MailOps", to: "/mailops" },
      { label: "Task Ownership", to: "/task-ownership" },
    ],
  },
  {
    label: "Business",
    items: [
      { label: "Consultant Business Suite", to: "/business-suite" },
      { label: "Revenue Pipeline", to: "/revenue-pipeline" },
      { label: "Revenue Intelligence", to: "/revenue-intelligence" },
      { label: "Opportunity Engine", to: "/opportunity-engine" },
      { label: "Client Portal", to: "/client-portal-admin" },
      { label: "Intelligence Reports", to: "/intelligence-reports" },
      { label: "Report Exports", to: "/report-exports" },
      { label: "Billing", to: "/billing" },
    ],
  },
  {
    label: "Maps",
    items: [
      { label: "Election Map", to: "/map" },
      { label: "Executive Operations Map", to: "/operations-map" },
      { label: "State Operations", to: "/state-operations" },
      { label: "State Operations Map", to: "/state-operations-map" },
      { label: "Campaign Opportunity Heatmap", to: "/campaign-opportunity-heatmap" },
    ],
  },
  {
    label: "Advanced",
    items: [
      { label: "Dashboard", to: "/dashboard" },
      { label: "Live Intelligence Layer", to: "/live-intelligence-layer" },
      { label: "Executive Intelligence", to: "/executive-intelligence" },
      { label: "Political Signals", to: "/political-signals" },
      { label: "Relationship Graph", to: "/relationship-graph" },
      { label: "Committee Intel", to: "/committee-intel" },
      { label: "Dark Money Exposure", to: "/dark-money-exposure" },
      { label: "Narrative Intelligence", to: "/narrative-intelligence" },
      { label: "Narrative Response", to: "/narrative-response" },
      { label: "Signal Matching", to: "/signal-matching" },
      { label: "AI Tactical", to: "/ai-tactical" },
      { label: "Power Rankings", to: "/power-rankings" },
    ],
  },
  {
    label: "Admin",
    items: [
      { label: "Firm Users", to: "/admin/firm-users" },
      { label: "Admin Platform Tour", to: "/platform-tour?mode=admin" },
      { label: "Launch Automation", to: "/launch-automation" },
      { label: "Live Data Refresh", to: "/live-data-refresh" },
      { label: "Launch Data Seeder", to: "/launch-data-seeder" },
      { label: "Beta Onboarding", to: "/beta-onboarding" },
      { label: "Launch Assets", to: "/launch-assets" },
      { label: "Database Stability", to: "/database-stability" },
      { label: "Launch Readiness", to: "/launch-readiness" },
      { label: "Launch QA", to: "/launch-qa" },
      { label: "Production Hardening", to: "/production-hardening" },
      { label: "Firm Invites", to: "/admin/firm-invites" },
      { label: "Candidate Profiles", to: "/admin/candidate-profiles" },
      { label: "Beta Access", to: "/admin/beta-access" },
      { label: "Live Intelligence", to: "/admin/live-intelligence" },
      { label: "Admin Alerts", to: "/admin/alerts" },
      { label: "Enterprise Leads", to: "/admin/enterprise-leads" },
    ],
  },
];

export const flattenedNavigation = navigationSections.flatMap((section) =>
  section.items.map((item) => ({
    ...item,
    section: section.label,
  }))
);